DO $$ 
BEGIN 
    ALTER TABLE public.posts DROP CONSTRAINT IF EXISTS posts_type_check; 
END $$;
ALTER TABLE public.posts ADD CONSTRAINT posts_type_check CHECK (type IN ('text', 'image', 'video', 'audio', 'agent', 'article'));
ALTER TABLE public.posts ALTER COLUMN prompt_ru DROP NOT NULL;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS body_html text;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS excerpt text;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS cover_url text;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS is_official boolean NOT NULL DEFAULT false;

INSERT INTO public.posts (type, status, published_at, is_official, author_id, prompt_ru, media, cover_url, title, excerpt, body_html) VALUES ( 'article', 'published', now(), true, '00cba612-ef89-4fe9-81c2-4770a1db44eb', NULL, '[]', '/community/02.jpg', 'Эволюция генеративного дизайна', 'Как нейросети меняют подход к визуальному творчеству и почему традиционные инструменты уступают место ИИ.', '<h2>Введение</h2><p>Современный мир дизайна стоит на пороге величайшей трансформации. <strong>Генеративные нейросети</strong> перестали быть просто игрушкой и превратились в мощный рабочий инструмент.</p><h3>Новые горизонты</h3><p>Раньше на создание сложной иллюстрации уходили часы, теперь — секунды. <em>Скорость итераций</em> позволяет дизайнерам фокусироваться на смыслах, а не на технической реализации.</p><ul><li>Быстрое прототипирование</li><li>Бесконечный поиск референсов</li><li>Автоматизация рутины</li></ul><blockquote>"ИИ не заменит дизайнера, но дизайнер с ИИ заменит дизайнера без ИИ."</blockquote><p>Рассмотрим сравнительную таблицу эффективности:</p><table><thead><tr><th>Процесс</th><th>Традиционно</th><th>С нейросетью</th></tr></thead><tbody><tr><td>Концепт-арт</td><td>4-8 часов</td><td>10-15 минут</td></tr><tr><td>Ретушь</td><td>30 минут</td><td>30 секунд</td></tr></tbody></table><ol><li>Выбор модели</li><li>Настройка промпта</li><li>Генерация вариантов</li></ol><p>Подробнее о методах читайте на <a href="https://era2.ai">сайте ЭРА2</a>.</p><img src="/community/03.jpg" alt="Пример генерации" /><p>Будущее уже здесь, и оно выглядит потрясающе.</p>' );
INSERT INTO public.posts (type, status, published_at, is_official, author_id, prompt_ru, media, cover_url, title, excerpt, body_html) VALUES ( 'article', 'published', now(), true, '75f32d9b-4cd0-45e3-a611-30a6b38ff6e9', NULL, '[]', '/community/05.jpg', 'Музыка будущего: ИИ в звукозаписи', 'Анализ влияния алгоритмов Suno и Udio на музыкальную индустрию и авторское право в 2026 году.', '<h2>Звуковая революция</h2><p>Музыкальная индустрия переживает тектонический сдвиг. <strong>Алгоритмы генерации звука</strong> научились создавать композиции, которые невозможно отличить от человеческих.</p><h3>Технологический стек</h3><p>Модели типа <em>Udio</em> используют диффузионные методы для синтеза не только голоса, но и сложных оркестровых аранжировок.</p><ul><li>Синтез вокала</li><li>Генерация мелодий</li><li>Мастеринг в один клик</li></ul><blockquote>"Мы наблюдаем демократизацию творчества в масштабе, которого не видели со времен изобретения интернета."</blockquote><p>Эффективность ИИ в производстве звука:</p><table><thead><tr><th>Тип работы</th><th>Человек</th><th>Нейросеть</th></tr></thead><tbody><tr><td>Джингл</td><td>2 дня</td><td>2 минуты</td></tr><tr><td>Саундтрек</td><td>Недели</td><td>Часы</td></tr></tbody></table><ol><li>Определение жанра</li><li>Ввод текстового описания</li><li>Пост-продакшн</li></ol><p>Слушайте примеры в нашем <a href="/community">разделе Аудио</a>.</p><img src="/community/03.jpg" alt="Студия будущего" /><p>Это не конец музыки, а ее новое начало.</p>' );
INSERT INTO public.posts (type, status, published_at, is_official, author_id, prompt_ru, media, cover_url, title, excerpt, body_html) VALUES ( 'article', 'published', now(), true, 'e1a7d46f-bbfe-483b-adcc-bbd6f63e3d7d', NULL, '[]', '/community/07.jpg', 'Агенты ERA2: Ваш личный цифровой разум', 'Подробный разбор архитектуры автономных агентов и их применение в решении повседневных бизнес-задач.', '<h2>Автономность и логика</h2><p><strong>Цифровые агенты</strong> — это следующий шаг в развитии LLM. Они не просто отвечают на вопросы, они действуют.</p><h3>Архитектура агента</h3><p>В основе лежит петля <em>планирования и исполнения</em>, дополненная инструментами внешнего доступа.</p><ul><li>Доступ к API</li><li>Память контекста</li><li>Самокритика и исправление</li></ul><blockquote>"Агент — это не чат-бот, это сотрудник, который работает 24/7 без выходных."</blockquote><p>Сравнение возможностей:</p><table><thead><tr><th>Функция</th><th>Обычная LLM</th><th>Агент ERA2</th></tr></thead><tbody><tr><td>Действия</td><td>Нет</td><td>Да</td></tr><tr><td>Доступ к файлам</td><td>Ограничен</td><td>Полный</td></tr></tbody></table><ol><li>Постановка цели</li><li>Разбиение на подзадачи</li><li>Исполнение</li></ol><p>Создать своего агента можно в <a href="/workspace">Воркспейсе</a>.</p><img src="/community/03.jpg" alt="Схема агента" /><p>Эффективность бизнеса теперь напрямую зависит от качества автоматизации.</p>' );

GRANT SELECT, INSERT, UPDATE, DELETE ON public.posts TO authenticated;
GRANT SELECT ON public.posts TO anon;
GRANT ALL ON public.posts TO service_role;
